### ISSUE TITLE
The same url the Exoplayer can play but Justplayer can’t 

### ISSUE THREAD

**Issue by aston314** [moneytoo/Player#113]
Why the same url: http://jx1090ys2.qx12345.top/hls/play/4c55b959b100a3a809aa9823963a1a5c6c5867b3be098dad5584d33a7e3996e2da5fef1940f8975cf48b341f252c7312d8e8f57611d84aa7134209b32c8e56e63cf41d06373d42daef3ef57fed30148aec9e%7C1622982487%7Cd6beefc4103850bc457dec165229ba00c9026eadf2f8e114%7Cadbb0bff49bf82652b204f0d9555a47e6beca6af4fc011cc407fd98f568b0c9bf8138f953fc8ec727d8ef97bb0e792e555356beff8895620%7C1839721196%7C800.m3u8

The exoplayer can play but Justplayer can’t not play?

**Comment by moneytoo** [comment]
I'm afraid that this url doesn't work for me at all.

**Comment by aston314** [comment]
I can’t play by the browser.

**Comment by aston314** [comment]
It can’t play by the browser

**Comment by aston314** [comment]
but the Exoplayer can.

**Comment by moneytoo** [comment]
Doesn't work for me in MX Player or VLC.

**Comment by aston314** [comment]
Yes I try some players: VLC MXPLAYER MPV JUSTPLAYER…all fail. But just the EXOPLAYER can play.

**Comment by moneytoo** [comment]
The url is probably tied to your connection and player (UA) you have used the first time accessing it and it cannot be shared.

```
2021-06-06 14:56:40.583 3185-30066/? E/ExoPlayerImplInternal: Playback error
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:580)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:214)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: com.google.android.exoplayer2.upstream.HttpDataSource$HttpDataSourceException: Unable to connect
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:357)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:201)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:101)
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:64)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:177)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:417)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.io.IOException: unexpected end of stream on com.android.okhttp.Address@45b32e1d
        at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:203)
        at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:129)
        at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:750)
        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:622)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:353)
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:201) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84) 
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:101) 
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:64) 
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:177) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:417) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919) 
     Caused by: java.io.EOFException: \n not found: size=0 content=...
        at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:202)
        at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:188)
        at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:129) 
        at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:750) 
        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:622) 
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475) 
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411) 
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542) 
        at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:353) 
        at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:201) 
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:84) 
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.checkOpened(DataSourceInputStream.java:101) 
        at com.google.android.exoplayer2.upstream.DataSourceInputStream.open(DataSourceInputStream.java:64) 
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:177) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:417) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919)
```
