### ISSUE TITLE
Time is not preserved on external load.

### ISSUE THREAD

**Issue by KyleSanderson** [moneytoo/Player#306]
I'm using Jellyfin to use launch Just Video. When this happens, progress is saved, but when you resume a video it does not jump to the passed time.

Logcat is giving this error on launch in brouken.player.

```
05-09 17:49:10.865  2871  3196 D Dcm1pAdapter: Instantiating an impl instance of DCM MetricsFacotry.
05-09 17:49:10.868 17469 17469 W System.err: java.io.FileNotFoundException: /data/user/0/com.brouken.player/files/positions (No such file or directory)
05-09 17:49:10.868 17469 17469 W System.err:    at java.io.FileInputStream.open0(Native Method)
05-09 17:49:10.868 17469 17469 W System.err:    at java.io.FileInputStream.open(FileInputStream.java:231)
05-09 17:49:10.868 17469 17469 W System.err:    at java.io.FileInputStream.<init>(FileInputStream.java:165)
05-09 17:49:10.868 17469 17469 W System.err:    at android.app.ContextImpl.openFileInput(ContextImpl.java:579)
05-09 17:49:10.868 17469 17469 W System.err:    at android.content.ContextWrapper.openFileInput(ContextWrapper.java:202)
05-09 17:49:10.868 17469 17469 W System.err:    at com.brouken.player.Prefs.loadPositions(Prefs.java:216)
05-09 17:49:10.868 17469 17469 W System.err:    at com.brouken.player.Prefs.<init>(Prefs.java:83)
05-09 17:49:10.868 17469 17469 W System.err:    at com.brouken.player.PlayerActivity.onCreate(PlayerActivity.java:211)
05-09 17:49:10.868 17469 17469 W System.err:    at android.app.Activity.performCreate(Activity.java:7151)
05-09 17:49:10.868 17469 17469 W System.err:    at android.app.Activity.performCreate(Activity.java:7141)
05-09 17:49:10.868 17469 17469 W System.err:    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
05-09 17:49:10.868 17469 17469 W System.err:    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2914)
05-09 17:49:10.868 17469 17469 W System.err:    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3075)
05-09 17:49:10.869 17469 17469 W System.err:    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
05-09 17:49:10.869 17469 17469 W System.err:    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
05-09 17:49:10.869 17469 17469 W System.err:    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
05-09 17:49:10.869 17469 17469 W System.err:    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1824)
05-09 17:49:10.869 17469 17469 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:106)
05-09 17:49:10.869 17469 17469 W System.err:    at android.os.Looper.loop(Looper.java:193)
05-09 17:49:10.869 17469 17469 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:6740)
05-09 17:49:10.869 17469 17469 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
05-09 17:49:10.869 17469 17469 W System.err:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
05-09 17:49:10.869 17469 17469 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

There's also this one that looks related.
```
05-09 17:49:10.916 17469 17469 W Bundle  : Key position expected Integer but value was a java.lang.Long.  The default value 0 was returned.
05-09 17:49:10.917 17469 17469 W Bundle  : Attempt to cast generated internal exception:
05-09 17:49:10.917 17469 17469 W Bundle  : java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer
05-09 17:49:10.917 17469 17469 W Bundle  :      at android.os.BaseBundle.getInt(BaseBundle.java:1036)
05-09 17:49:10.917 17469 17469 W Bundle  :      at android.os.BaseBundle.getInt(BaseBundle.java:1018)
05-09 17:49:10.917 17469 17469 W Bundle  :      at com.brouken.player.PlayerActivity.onCreate(PlayerActivity.java:290)
05-09 17:49:10.917 17469 17469 W Bundle  :      at android.app.Activity.performCreate(Activity.java:7151)
05-09 17:49:10.917 17469 17469 W Bundle  :      at android.app.Activity.performCreate(Activity.java:7141)
05-09 17:49:10.917 17469 17469 W Bundle  :      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
05-09 17:49:10.917 17469 17469 W Bundle  :      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2914)
05-09 17:49:10.917 17469 17469 W Bundle  :      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3075)
05-09 17:49:10.917 17469 17469 W Bundle  :      at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
05-09 17:49:10.917 17469 17469 W Bundle  :      at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
05-09 17:49:10.917 17469 17469 W Bundle  :      at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
05-09 17:49:10.917 17469 17469 W Bundle  :      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1824)
05-09 17:49:10.917 17469 17469 W Bundle  :      at android.os.Handler.dispatchMessage(Handler.java:106)
05-09 17:49:10.917 17469 17469 W Bundle  :      at android.os.Looper.loop(Looper.java:193)
05-09 17:49:10.917 17469 17469 W Bundle  :      at android.app.ActivityThread.main(ActivityThread.java:6740)
05-09 17:49:10.917 17469 17469 W Bundle  :      at java.lang.reflect.Method.invoke(Native Method)
05-09 17:49:10.917 17469 17469 W Bundle  :      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
05-09 17:49:10.917 17469 17469 W Bundle  :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

I'm using a AMZN Firestick Max 4K.

**Comment by moneytoo** [comment]
When Jellyfin launches Just Player, it specifies starting position so Just Player resumes at that position. When you return back to Jellyfin, Just Player passes the current playback position back to Jellyfin. This works in other media library apps (including Nova Video Player etc.), however Jellyfin reads returned position only from 3 hard coded external players ([mpv, MX Player and VLC](https://github.com/jellyfin/jellyfin-android/blob/v2.4.4/app/src/main/java/org/jellyfin/mobile/bridge/ExternalPlayer.kt#L59-L61)). Jellyfin ignores return values of other players implementing the MX Player/VLC API as well. Raise an issue with Jellyfin devs to resolve this.

**Comment by KyleSanderson** [comment]
Jellyfin is recording the time correctly from Just Player, Just Player is not honouring the time passed to the player from Jellyfin. The issue is Resume Media -> Just Player restarts. I've also had issues with this on Nova, but I'm unclear on if it's the same logcat errors.

**Comment by moneytoo** [comment]
Resume in Just Player works for me. When I launch and stop VLC, it updates position in Jellyfin so when I then launch Just Player, it correctly resumes but the position returned back to Jellyfin is ignored.

It's really about the action name check in Jellyfin (as linked in my previous comment). However I'm going to switch to the MX Player action name so it will make it work with Jellyfin and possibly also improve compatibility with other apps (#203). (And hopefully won't brake anything.)

**Comment by KyleSanderson** [comment]
I apologize for asking you to look into this - Jellyfin is trash and I've finally returned to Kodi about an hour ago.

For completeness I've gotten Just Player running with mode switching to take over the DV gap. Here's some documentation along with some editorial - hopefully it helps the next person save a ton of time. https://github.com/moneytoo/Player/discussions/310
