### ISSUE TITLE
Bug while opening player

### ISSUE THREAD

**Issue by divyansh10101** [moneytoo/Player#40]
https://del.dog/nupilelopo

```
time: 1612197716649
msg: java.lang.RuntimeException: Cannot initialize effect engine for type: fe3199be-aed0-413f-87bb-11260eb63cf1 Error: -3
stacktrace: java.lang.RuntimeException: Cannot initialize effect engine for type: fe3199be-aed0-413f-87bb-11260eb63cf1 Error: -3
	at android.media.audiofx.AudioEffect.<init>(AudioEffect.java:521)
	at android.media.audiofx.AudioEffect.<init>(AudioEffect.java:488)
	at android.media.audiofx.AudioEffect.<init>(AudioEffect.java:462)
	at android.media.audiofx.LoudnessEnhancer.<init>(LoudnessEnhancer.java:80)
	at com.brouken.player.PlayerActivity$3.onAudioSessionId(PlayerActivity.java:561)
	at com.google.android.exoplayer2.SimpleExoPlayer.notifyAudioSessionIdSet(SimpleExoPlayer.java:2037)
	at com.google.android.exoplayer2.SimpleExoPlayer.access$2900(SimpleExoPlayer.java:75)
	at com.google.android.exoplayer2.SimpleExoPlayer$ComponentListener.onAudioSessionId(SimpleExoPlayer.java:2231)
	at com.google.android.exoplayer2.audio.AudioRendererEventListener$EventDispatcher.lambda$audioSessionId$6$AudioRendererEventListener$EventDispatcher(AudioRendererEventListener.java:177)
	at com.google.android.exoplayer2.audio.-$$Lambda$AudioRendererEventListener$EventDispatcher$MnqtJ56WvRd4g2TMAefvhP3gwCk.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7661)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by divyansh10101** [comment]
I was opening an mkv file

**Comment by moneytoo** [comment]
What device model and Android version do you use? Is that caused by the specific mkv file or does it crash with any video file?

**Comment by divyansh10101** [comment]
> What device model and Android version do you use? Is that caused by the specific mkv file or does it crash with any video file?

Redmi note 5 pro
Custom rom=>Octavi 1.5
I only have one mkv file in my phone.
Sometime when I try to open from file manager it crashes sometimes. Sometime it opens and when that mkv file is selected in player,player crashes as I open the player.

**Comment by divyansh10101** [comment]
[Feature] play audio only from video

**Comment by divyansh10101** [comment]
https://del.dog/elemegnexi

**Comment by divyansh10101** [comment]
Bug while opening the app while selected mkv file

**Comment by moneytoo** [comment]
It might be quite possibly because of the custom rom. However I noticed same RuntimeException in reports from other devices so I guess it's better just to live without an optional volume boost instead of a crash. Cause I have no idea what else I can do with that.

**Comment by divyansh10101** [comment]
Do you have any option to turn it off in the app well I'm not using that option

**Comment by moneytoo** [comment]
It should be fixed and will be available in the next update. It should be a matter of a few days.

**Comment by divyansh10101** [comment]
OK
