### ISSUE TITLE
i have implement playlist related to playing video

### ISSUE THREAD

**Issue by JB2636** [moneytoo/Player#88]
@moneytoo @weblate @sr093906 @kyelbek @comradekingu 

https://user-images.githubusercontent.com/57219773/114829685-04e52900-9de9-11eb-90b7-32021d776979.mp4

i get error in below line..
### **playerView.setPlayer(player);**

error.
E/AndroidRuntime: FATAL EXCEPTION: android.bg
    Process: com.video.videoplayer.videoapp, PID: 6493
    java.lang.IllegalStateException
        at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:86)
        at com.google.android.exoplayer2.ui.StyledPlayerView.setPlayer(StyledPlayerView.java:568)
        at com.video.videoplayer.videoapp.videoplayer.activity.VideoPlayerActivity.initializePlayer(VideoPlayerActivity.java:758)
        at com.video.videoplayer.videoapp.videoplayer.activity.VideoPlayerActivity.onStart(VideoPlayerActivity.java:464)
        at com.video.videoplayer.videoapp.videoplayer.activity.VideoPlayerActivity.relatedVideo_onclick_position(VideoPlayerActivity.java:1392)
        at com.video.videoplayer.videoapp.videoplayer.adapter.RelatedVideoData$2.lambda$onClick$0$RelatedVideoData$2(RelatedVideoData.java:179)
        at com.video.videoplayer.videoapp.videoplayer.adapter.-$$Lambda$RelatedVideoData$2$QAfOSWsuQ9sD69wjMwANhygLaqY.onScanCompleted(Unknown Source:4)
        at android.media.MediaScannerConnection.runCallBack(MediaScannerConnection.java:277)
        at android.media.MediaScannerConnection.lambda$scanFile$1(MediaScannerConnection.java:244)
        at android.media.-$$Lambda$MediaScannerConnection$X7K_c7l7bfQR6Mg9eCJVPmLMn6I.run(Unknown Source:6)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:233)
        at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by Rocky2242** [comment]
Can I see your repo...

**Comment by moneytoo** [comment]
This player is just a standalone app. Any other usage is not supported (it's not a library). Feel free to use the code as you wish though.

**Comment by Rocky2242** [comment]
> @moneytoo @weblate @sr093906 @kyelbek @comradekingu
> 
>  21-04-14-19-02-50.online-video-cutter.com.1.mp4 
> i get error in below line..
> 
> ### **playerView.setPlayer(player);**
> error.
> E/AndroidRuntime: FATAL EXCEPTION: android.bg
> Process: com.video.videoplayer.videoapp, PID: 6493
> java.lang.IllegalStateException
> at com.google.android.exoplayer2.util.Assertions.checkState(Assertions.java:86)
> at com.google.android.exoplayer2.ui.StyledPlayerView.setPlayer(StyledPlayerView.java:568)
> at com.video.videoplayer.videoapp.videoplayer.activity.VideoPlayerActivity.initializePlayer(VideoPlayerActivity.java:758)
> at com.video.videoplayer.videoapp.videoplayer.activity.VideoPlayerActivity.onStart(VideoPlayerActivity.java:464)
> at com.video.videoplayer.videoapp.videoplayer.activity.VideoPlayerActivity.relatedVideo_onclick_position(VideoPlayerActivity.java:1392)
> at com.video.videoplayer.videoapp.videoplayer.adapter.RelatedVideoData$2.lambda$onClick$0$RelatedVideoData$2(RelatedVideoData.java:179)
> at com.video.videoplayer.videoapp.videoplayer.adapter.-$$Lambda$RelatedVideoData$2$QAfOSWsuQ9sD69wjMwANhygLaqY.onScanCompleted(Unknown Source:4)
> at android.media.MediaScannerConnection.runCallBack(MediaScannerConnection.java:277)
> at android.media.MediaScannerConnection.lambda$scanFile$1(MediaScannerConnection.java:244)
> at android.media.-$$Lambda$MediaScannerConnection$X7K_c7l7bfQR6Mg9eCJVPmLMn6I.run(Unknown Source:6)
> at android.os.Handler.handleCallback(Handler.java:938)
> at android.os.Handler.dispatchMessage(Handler.java:99)
> at android.os.Looper.loop(Looper.java:233)
> at android.os.HandlerThread.run(HandlerThread.java:67)

I want to see your repo.  Pls. Reply...

**Comment by JB2636** [comment]
@Rocky2242

can we discuss in skype.

**Comment by Rocky2242** [comment]
Ofcourse before that can you share your project/repo.. so I can get a brief....

**Comment by JB2636** [comment]
Actually, I don't have repo. ans it is an ongoing project , So, I cannot share it. But we can find other way to work round. Maybe I can let you know about the working by sharing screen or Anydesk.

Skype id. live:jaykishan12.savani

**Comment by Rocky2242** [comment]
Can you tell me how you have made the videos list click and play....
